# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.cache/wt [current_project]
set_property parent.project_path E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/Similary_LUT.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/asyn_rst_syn.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/cmos_capture_data.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/ddr3_fifo_ctrl.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/ddr3_rw.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/ddr3_top.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/dvi_encoder.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/dvi_transmitter_top.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/hdmi_top.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/i2c_dri.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/i2c_ov5640_rgb565_cfg.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/line_shift_ram_8bit.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/ov5640_dri.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/rgb2ycbcr.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/serializer_10_to_1.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/video_driver.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/vip.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/vip_gray_blif.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/vip_matrix_generate_3x3_8bit.v
  E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/new/ov5640_hdmi_median_filter.v
}
read_ip -quiet E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

read_ip -quiet E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files E:/code/luoyuedong/fpga/blif/blif_10_16/ov5460_hdmi_blif/ov5460_hdmi_blif.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ov5640_hdmi_bli_filter -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ov5640_hdmi_bli_filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ov5640_hdmi_bli_filter_utilization_synth.rpt -pb ov5640_hdmi_bli_filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
